export default [
    {
        paletteName : 'Material UI Colors',
        id :'material-ui-colors',
        emojis :'🎨',
        colors : [
            {name : 'red', color: '#F44336'},
            {name : 'pink', color: '#E91E63'},
            {name : 'purple', color: '#9C27B0'},
            {name : 'deeppurple', color: '#673AB7'},
            {name : 'indigo', color: '#3F5185'},
            {name : 'blue', color: '#2196F3'},
            {name : 'lightblue', color: '#03A9F4'},
            {name: "cyan", color: "#00BCD4" },
            {name: "teal", color: "#009688" },
            {name: "green", color: "#4CAF50" },
            {name: "lightgreen", color: "#8BC34A" },
            {name : 'Lime', color: '#00BCD4'},
            {name : 'yellow', color: '#009688'},
            {name : 'anber', color: '#4CAF50'},
            {name : 'orange', color: '#9BC34A'},
            {name : 'deeporange', color: '#FF2722'},
            {name : 'brown', color: '#795548'},
            {name : 'grey', color: '#9E9E9E'},
            {name : 'bluegrey', color: '#607D88'}
        ]
    },
    {
        paletteName : 'Flat UI Colors v1',
        id :'flat-ui-colors-v1',
        emojis :'🤙',
        colors : [
            {name : 'Turquoise', color: '#1abc9c'},
            {name : 'Emerale', color: '#2ECC71'},
            {name : 'PeterRiver', color: '#3498DB'},
            {name : 'Amethyst', color: '#9B59B6'},
            {name : 'WetAsphalt', color: '#34495E'},
            {name : 'GreenSea', color: '#27AE60'},
            {name : 'Nephritis', color: '#2988B9'},
            {name : 'BelizeHole', color: '#8E44AD'},
            {name : 'Wisteria', color: '#2C3E50'},
            {name : 'MidnightBlue', color: '#F1C40F'},
            {name : 'SunFlower', color: '#E67E22'},
            {name : 'Carrot', color: '#E74C3C'},
            {name : 'Alizarin', color: '#E67E22'},
            {name : 'Clouds', color: '#E74C3C'},
            {name : 'Concrete', color: '#ECF0F1'},      
            {name : 'Orange', color: '#95A5A6'},
            {name : 'Pumpkin', color: '#F39C12'},
            {name : 'Pomegranate', color: '#D35400'},      
            {name : 'Silver', color: '#C0392B'},
            {name : 'Asbestos', color: '#7F8C8D'}   
        ]
    },
    {
        paletteName : 'Flat UI Colors Dutch',
        id :'flat-ui-colors-dutch',
        emojis :'🇳🇱',
        colors : [
            {name : 'Sunflower', color: '#ffc312'},
            {name : 'Emergos', color: '#C4E538'},
            {name : 'BlueMartina', color: '#12CBC4'},
            {name : 'lavenderRose', color: '#FDA7DF'},
            {name : 'BaraRose', color: '#ED4C67'},
            {name : 'RadiantYellow', color: '#F79F1F'},
            {name : 'AndroidGreen', color: '#A3CB38'},
            {name : 'MediteraneanSea', color: '#1289A7'},
            {name : 'LavenderTea', color: '#D980FA'},
            {name : 'VerryBerry', color: '#853471'},
            {name : 'PuffinsBill', color: '#EE5A24'},
            {name : 'PixelatedGrass', color: '#009432'},
            {name : 'MerchantMarineBlue', color: '#0652DD'},
            {name : 'ForgottenPurple', color: '#9980FA'},
            {name : 'HollyHock', color: '#833471'},  
            {name : 'RedPignent', color: '#EA2827'},
            {name : 'TurkishAqua', color: '#006266'},
            {name : '2000LeaguesUnderTheSea', color: '#1B1464'},      
            {name : 'CircumorBitalRing', color: '#5758BB'},
            {name : 'MagentaPurple', color: '#6F1E51'}   
        ]
    }
    ,
    {
        paletteName : 'Flat UI Colors American',
        id :'flat-ui-colors-american',
        emojis :'🇺🇸',
        colors : [
            {name : 'LightGreenIsBlue', color: '#55efc4'},
            {name : 'FadedPoster', color: '#81ecec'},
            {name : 'GreenDarnerTail', color: '#74b9ff'},
            {name : 'ShyMoment', color: '#a29bfe'},
            {name : 'CityLights', color: '#dfe6e9'},
            {name : 'MintLeaf', color: '#80b894'},
            {name : 'RobinsEggBlue', color: '#80cec9'},
            {name : 'ElectronBlue', color: '#0984e3'},
            {name : 'ExodusFruit', color: '#6c5ce7'},
            {name : 'SoothingBreeze', color: '#b2bec3'},
            {name : 'SourLenon', color: '#ffeaa7'},
            {name : 'FirstDate', color: '#fab1a0'},
            {name : 'PinkGlamour', color: '#ff7675'},
            {name : 'Pico8Pink', color: '#fd79a8'},
            {name : 'AmericanRiver', color: '#636e72'},
            {name : 'BrightYarrow', color: '#fdcb6e'},  
            {name : 'OrrangeVille', color: '#e17055'},
            {name : 'Chi-Gong', color: '#d63031'},
            {name : 'PrunusAvium', color: '#e84393'},     
            {name : 'DraculaOrchid', color: '#2d3436'}
        ]
    }
    ,
    {
        paletteName : 'Flat UI Colors Aussie',
        id :'flat-ui-colors-aussie',
        emojis :'🇦🇺',
        colors : [
            {name : 'Beekeeper', color: '#f6e58d'},
            {name : 'SpicedNectarine', color: '#ffbe76'},
            {name : 'PinkGlamour', color: '#ff7979'},
            {name : 'JuneBlue', color: '#badc58'},
            {name : 'CostalBreeze', color: '#dff9fb'},
            {name : 'Turbo', color: '#f9ca24'},
            {name : 'QuinceJelly', color: '#f0932b'},
            {name : 'CarminePink', color: '#eb4d4b'},
            {name : 'PureApple', color: '#6ab04c'},
            {name : 'HintOfIcePack', color: '#c7ecee'},
            {name : 'MiddleBlue', color: '#7ed6df'},
            {name : 'Heliotrope', color: '#e056fd'},
            {name : 'ExodusFruit', color: '#686de0'},
            {name : 'DeepKoamaru', color: '#30336b'},
            {name : 'SoaringEagle', color: '#95afc0'},      
            {name : 'GreelandGreen', color: '#22a6b3'},
            {name : 'SteelPink', color: '#be2edd'},
            {name : 'Blurple', color: '#4b34d4'},      
            {name : 'DeepCove', color: '#130f40'},
            {name : 'WizardGrey', color: '#535c68'}   
        ]
    }
    ,
    {
        paletteName : 'Flat UI Colors British',
        id :'flat-ui-colors-british',
        emojis :'"🇬🇧',
        colors : [
            {name : 'PotossPylon', color: '#00a8ff'},
            {name : 'Perinwinkle', color: '#9c88ff'},
            {name : 'Rise-N-Shine', color: '#fbc531'},
            {name : 'DownLoadProgress', color: '#4cd137'},
            {name : 'Seabrook', color: '#487eb8'},
            {name : 'VanaDyBlue', color: '#0097e6'},
            {name : 'MattPurple', color: '#8c7ae6'},
            {name : 'NanohanachaGold', color: '#e1b12c'},
            {name : 'SkirretGreen', color: '#40739e'},
            {name : 'NasturicanFlower', color: '#e84118'},
            {name : 'LynxWhite', color: '#f5f6fa'},
            {name : 'BlueberrySoda', color: '#7f8fa6'},
            {name : 'MazarineBlue', color: '#273c75'},
            {name : 'BlueNights', color: '#353b48'},      
            {name : 'HarleyOrange', color: '#c23616'},
            {name : 'HintOfPensive', color: '#dcdde1'},
            {name : 'ChainGangGrey', color: '#718093'},      
            {name : 'PicoVoid', color: '#192a56'},
            {name : 'ElectroMagnetic', color: '#2f3640'}   
        ]
    }
    ,
    {
        paletteName: "Flat UI Colors Spanish",
        id: "flat-ui-colors-spanish",
        emoji: "🇪🇸",
        colors: [
          { name: "JacksonsPurple", color: "#40407a" },
          { name: "C64Purple", color: "#706fd3" },
          { name: "SwanWhite", color: "#f7f1e3" },
          { name: "SummerSky", color: "#34ace0" },
          { name: "CelestialGreen", color: "#33d9b2" },
          { name: "LuckyPoint", color: "#2c2c54" },
          { name: "Liberty", color: "#474787" },
          { name: "HotStone", color: "#aaa69d" },
          { name: "DevilBlue", color: "#227093" },
          { name: "PalmSpringsSplash", color: "#218c74" },
          { name: "FlourescentRed", color: "#ff5252" },
          { name: "SyntheticPumpkin", color: "#ff793f" },
          { name: "CrocodileTooth", color: "#d1ccc0" },
          { name: "MandarinSorbet", color: "#ffb142" },
          { name: "SpicedButterNut", color: "#ffda79" },
          { name: "EyeOfNewt", color: "#b33939" },
          { name: "ChileanFire", color: "#cd6133" },
          { name: "GreyPorcelain", color: "#84817a" },
          { name: "AlamedaOchre", color: "#cc8e35" },
          { name: "Desert", color: "#ccae62" }
        ]
      }
    ,
    {
        paletteName : 'Flat UI Colors Canada',
        id :'flat-ui-colors-Canada',
        emojis :'',
        colors : [
            {name : 'Jifflypuff', color: '#ff9ff3'},
            {name : 'LianHongLotusPink', color: '#f368e0'},
            {name : 'JadaDust', color: '#00d2d3'},
            {name : 'AquatVelvet', color: '#01a3a4'},
            {name : 'CasandoraYellow', color: '#feca57'},
            {name : 'DoubleDragonSkin', color: '#ff9f43'},
            {name : 'JoustBlue', color: '#54a0ff'},
            {name : 'BleuDeFrance', color: '#2e86de'},
            {name : 'PastelRed', color: '#ff6b6b'},
            {name : 'Amour', color: '#ee5253'},
            {name : 'NasuPurple', color: '#5f27cd'},
            {name : 'BlueBell', color: '#341f97'},
            {name : 'Megaman', color: '#48dbfb'},
            {name : 'Cyanite', color: '#0abde3'},      
            {name : 'LightBlueBallerina', color: '#c8d6e5'},
            {name : 'StormPetrel', color: '#8395a7'},
            {name : 'WildCaribbeanGreen', color: '#1dd1a1'},      
            {name : 'DarkMountainMeadow', color: '#10ac84'},
            {name : 'FuelTown', color: '#576574'},
            {name : 'ImperialPrimer', color: '#222f3e'}   
        ]
    }
    ,
    {
        paletteName: "Flat UI Colors Indian",
        id: "flat-ui-colors-indian",
        emoji: "🇮🇳",
        colors: [
          { name: "OrchidOrange", color: "#FEA47F" },
          { name: "SpiroDiscoBall", color: "#25CCF7" },
          { name: "HoneyGlow", color: "#EAB543" },
          { name: "SweetGarden", color: "#55E6C1" },
          { name: "FallingStar", color: "#CAD3C8" },
          { name: "RichGardenia", color: "#F97F51" },
          { name: "ClearChill", color: "#1B9CFC" },
          { name: "WhitePepper", color: "#F8EFBA" },
          { name: "Keppel", color: "#58B19F" },
          { name: "ShipsOfficer", color: "#2C3A47" },
          { name: "FieryFuchsia", color: "#B33771" },
          { name: "BlueBell", color: "#3B3B98" },
          { name: "GeorgiaPeach", color: "#FD7272" },
          { name: "OasisStream", color: "#9AECDB" },
          { name: "BrightUbe", color: "#D6A2E8" },
          { name: "MagentaPurple", color: "#6D214F" },
          { name: "EndingNavyBlue", color: "#182C61" },
          { name: "SasquatchSocks", color: "#FC427B" },
          { name: "PineGlade", color: "#BDC581" },
          { name: "HighlighterLavender", color: "#82589F" }
        ]
      }
    ,
    {
        paletteName : 'Flat UI Colors French',
        id :'flat-ui-colors-french',
        emojis :"🇫🇷",
        colors : [
            {name :'FlatFlesh' , color :'#fad390'},
            {name :'SquashBlossom' , color :'#f6b93b'},
            {name :'IcelandPoppy' , color :'#fa983a'},
            {name :'CarrotOrrange' , color :'#e58e26'},
            {name :'MelonMelody' , color :'#f8c291'},
            {name :'MandarinRed' , color :'#e55039'},
            {name :'TomatoRed' , color :'#eb2f06'},
            {name :'JalapenoRed' , color :'#b71540'},
            {name :'Livid' , color :'#6a89cc'},
            {name :'AzraqBlue' , color :'#4a69bd'},
            {name :'GuanGLanBlue' , color :'#1e3799'},
            {name :'DarkSapphire' , color :'#0c2461'},
            {name :'Spray' , color :'#82ccdd'},
            {name :'Dupain' , color :'#60a3bc'},
            {name :'GoodSamaritan' , color :'#3c6382'},
            {name :'ForestBlues' , color :'#0a3d62'},
            {name :'ParadiseGreen' , color :'#b8e994'},
            {name :'AuroraGreen' , color :'#78e08f'},
            {name :'Waterfall' , color :'#38ada9'},
            {name :'ReefEncounter' , color :'#079992'},
        ]
    }
    
]